# Generated by Django 3.0.5 on 2020-12-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201215_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='img',
        ),
    ]
